services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine
    container_name: redis
    command: ['redis-server', '--requirepass', 'your-redis-password']
    environment:
      REDIS_PASSWORD: your-redis-password
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
